sudo: false
cache: bundler
language: ruby
gemfile: travis-Gemfile
bundler_args: --gemfile=travis-Gemfile --retry=3 --jobs=3
rvm:
  - 2.0
  - 2.1
  - 2.2
env:
  - BUNDLE_GEMFILE=travis-Gemfile
cache: 
  - bundler
before_script:
  - bundle exec berks install
script:
  - bundle exec foodcritic -t ~FC002 -f any .
  - bundle exec rubocop
  - bundle exec rspec
